"""
Signal Module - Trading Signal Representation

Defines standardized signals that strategies generate. Signals represent
trading intentions before they become actual orders.

Flow: Strategy → Signal → Position Sizer → Risk Manager → Order → Execution
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
from typing import Dict, Any, Optional


class SignalDirection(IntEnum):
    """Signal direction with integer values for math operations."""
    BUY = 1      # Open long position
    SELL = -1    # Open short position
    HOLD = 0     # No action
    CLOSE = 2    # Close any position


@dataclass
class Signal:
    """
    Trading signal generated by strategies.

    Required:
        symbol: Ticker symbol (e.g., "SBIN")
        direction: BUY/SELL/HOLD/CLOSE
        timestamp: When signal was generated
        strength: Signal strength (0.0 - 1.0)
        confidence: Strategy confidence (0.0 - 1.0)

    Optional:
        quantity: Number of shares (None = let position sizer decide)
        metadata: Additional data for logging/debugging
        reasoning: Why signal was generated
        target_price: Take-profit target
        stop_loss: Stop loss price
        order_type: 'MARKET', 'LIMIT', or 'STOP'
        limit_price: Price for LIMIT orders
    """

    # Required fields
    symbol: str
    direction: SignalDirection
    timestamp: datetime
    strength: float
    confidence: float

    # Optional fields
    quantity: Optional[int] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    reasoning: Optional[str] = None
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    order_type: str = 'MARKET'
    limit_price: Optional[float] = None

    def __post_init__(self):
        """Validate signal fields."""
        # Validate and standardize symbol
        if not self.symbol or not self.symbol.strip():
            raise ValueError("symbol cannot be empty")
        self.symbol = self.symbol.strip().upper()

        # Validate ranges
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(f"strength must be 0.0-1.0, got {self.strength}")

        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"confidence must be 0.0-1.0, got {self.confidence}")

        # Validate quantity
        if self.quantity is not None and self.quantity <= 0:
            raise ValueError(f"quantity must be positive, got {self.quantity}")

        # Validate prices
        if self.target_price is not None and self.target_price <= 0:
            raise ValueError(f"target_price must be positive, got {self.target_price}")

        if self.stop_loss is not None and self.stop_loss <= 0:
            raise ValueError(f"stop_loss must be positive, got {self.stop_loss}")

        if self.limit_price is not None and self.limit_price <= 0:
            raise ValueError(f"limit_price must be positive, got {self.limit_price}")

        # Validate order type
        if self.order_type not in ['MARKET', 'LIMIT', 'STOP']:
            raise ValueError(f"order_type must be MARKET/LIMIT/STOP, got {self.order_type}")

        # LIMIT orders require limit_price
        if self.order_type == 'LIMIT' and self.limit_price is None:
            raise ValueError("limit_price required for LIMIT orders")

    def is_entry(self) -> bool:
        """Check if signal opens a new position."""
        return self.direction in (SignalDirection.BUY, SignalDirection.SELL)

    def is_exit(self) -> bool:
        """Check if signal closes a position."""
        return self.direction == SignalDirection.CLOSE

    def is_actionable(self) -> bool:
        """Check if signal requires action."""
        return self.direction != SignalDirection.HOLD

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for logging/storage."""
        return {
            'symbol': self.symbol,
            'direction': self.direction.name,
            'direction_value': self.direction.value,
            'timestamp': self.timestamp.isoformat(),
            'strength': self.strength,
            'confidence': self.confidence,
            'quantity': self.quantity,
            'metadata': self.metadata,
            'reasoning': self.reasoning,
            'target_price': self.target_price,
            'stop_loss': self.stop_loss,
            'order_type': self.order_type,
            'limit_price': self.limit_price,
        }

    def __str__(self) -> str:
        """Human-readable representation."""
        return (
            f"Signal({self.direction.name} {self.symbol} "
            f"@ {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}, "
            f"strength={self.strength:.2f}, confidence={self.confidence:.2f})"
        )

    def __repr__(self) -> str:
        """Developer representation."""
        return (
            f"Signal(symbol='{self.symbol}', direction={self.direction.name}, "
            f"timestamp={self.timestamp!r}, strength={self.strength}, "
            f"confidence={self.confidence})"
        )
